---
output:
  pdf_document:
    fig_caption: yes
    template: ./resources/aog-latex-ms.tex
fontfamily: mathpazo
fontsize: 11pt
appendix: true
appendixletter: S
pagenumber: 35
---

# Supplementary Appendix

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message=FALSE)
library(here)
source(here("analysis","check_packages.R"))
source(here("analysis","useful_functions.R"))
load(here("analysis","output","models_sensivity_mar_market.RData"))
models_census_pentagon_state <- models_census_pentagon
models_acs1980_pentagon_state <- models_acs1980_pentagon
load(here("analysis","output","models.RData"))
library(ggtext)

my_palette <- c("#7b3294","#008837","#a6dba0")
```


```{r theme, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE, include=FALSE}
theme_mine <- function() {
  theme_bw()+
    theme(axis.title = element_text(size=10), 
          axis.text = element_text(size=8),
          legend.text=element_text(size=7),
          legend.title=element_text(size=8),
          legend.key.size = unit(0.8,"line"),
          strip.text = element_text(size=9),
          legend.position = "bottom")
}
```

```{r create-coef-map}
coef_map <- list("agediff"="age difference",
                 "I(agediff^2)"="age difference, squared",
                 "hypergamyTRUE"="female educational hypergamy",
                 "hypogamyTRUE"="female educational hypogamy",
                 "edcross_hsTRUE"="Ed. crossing, high school",
                 "edcross_scTRUE"="Ed. crossing, some college",
                 "edcross_cTRUE"="Ed. crossing, college",
                 "race_exog_pentBlack.AIAN"="AIAN-Black exogamy",
                 "race_exog_pentAIAN.E&SE Asian"="AIAN-E/SE Asian exogamy",
                 "race_exog_pentAIAN.Latino"="AIAN-Latino exogamy",
                 "race_exog_pentAIAN.South Asian"="AIAN-S Asian exogamy",
                 "race_exog_pentWhite.AIAN"="AIAN-White exogamy",
                 "race_exog_pentBlack.E&SE Asian"="Black-E/SE Asian exogamy",
                 "race_exog_pentBlack.Latino"="Black-Latino exogamy",
                 "race_exog_pentBlack.South Asian"="Black-S Asian exogamy",
                 "race_exog_pentWhite.Black"="Black-White exogamy",
                 "race_exog_pentE&SE Asian.South Asian"="E/SE Asian-S Asian exogamy",
                 "race_exog_pentLatino.E&SE Asian"="E/SE Asian-Latino exogamy",
                 "race_exog_pentWhite.E&SE Asian"="E/SE Asian/White exogamy",
                 "race_exog_pentLatino.South Asian"="Latino-S Asian exogamy",
                 "race_exog_pentWhite.Latino"="Latino-White exogamy",
                 "race_exog_pentWhite.South Asian"="S Asian-White exogamy",
                 "race_exog_pentLatino.Latino"="Latino ethnic exogamy",
                 "race_exog_pentE&SE Asian.E&SE Asian"="E/SE Asian ethnic exogamy",
                 "race_exog_extendedBlack.AIAN"="AIAN-Black exogamy",
                 "race_exog_extendedAIAN.E&SE Asian"="AIAN-E/SE Asian exogamy",
                 "race_exog_extendedAIAN.Latino"="AIAN-Latino exogamy",
                 "race_exog_extendedAIAN.South Asian"="AIAN-S Asian exogamy",
                 "race_exog_extendedWhite.AIAN"="AIAN-White exogamy",
                 "race_exog_extendedBlack.E&SE Asian"="Black-E/SE Asian exogamy",
                 "race_exog_extendedBlack.Latino"="Black-Latino exogamy",
                 "race_exog_extendedBlack.South Asian"="Black-S Asian exogamy",
                 "race_exog_extendedWhite.Black"="Black-White exogamy",
                 "race_exog_extendedE&SE Asian.South Asian"="E/SE Asian-S Asian exogamy",
                 "race_exog_extendedLatino.E&SE Asian"="E/SE Asian-Latino exogamy",
                 "race_exog_extendedWhite.E&SE Asian"="E/SE Asian/White exogamy",
                 "race_exog_extendedLatino.South Asian"="Latino-S Asian exogamy",
                 "race_exog_extendedWhite.Latino"="Latino-White exogamy",
                 "race_exog_extendedWhite.South Asian"="S Asian-White exogamy",
                 "race_exog_extendedLatino.Latino"="Latino ethnic exogamy",
                 "race_exog_extendedE&SE Asian.E&SE Asian"="E/SE Asian ethnic exogamy",
                 "race_exog_extendedAsian Indian.Pakistani"="Asian Indian-Pakistani exogamy",
                 "race_exog_extendedBlack.Chinese"="Black-Chinese exogamy",
                 "race_exog_extendedBlack.Colombian"="Black-Colombian exogamy",
                 "race_exog_extendedBlack.Cuban"="Black-Cuban exogamy",
                 "race_exog_extendedBlack.Dominican"="Black-Dominican exogamy",
                 "race_exog_extendedBlack.Ecuadorian"="Black-Ecuadorian exogamy",
                 "race_exog_extendedBlack.Filipino"="Black-Filipino exogamy",
                 "race_exog_extendedBlack.Guatemalan"="Black-Guatemalan exogamy",
                 "race_exog_extendedBlack.Japanese"="Black-Japanese exogamy",
                 "race_exog_extendedBlack.Korean"="Black-Korean exogamy",
                 "race_exog_extendedBlack.Mexican"="Black-Mexican exogamy",
                 "race_exog_extendedBlack.Peruvian"="Black-Peruvian exogamy",
                 "race_exog_extendedBlack.Puerto Rican"="Black-PR exogamy",
                 "race_exog_extendedBlack.Salvadorian"="Black-Salvadorian exogamy",
                 "race_exog_extendedBlack.Vietnamese"="Black-Vietnamese exogamy",
                 "race_exog_extendedChinese.Filipino"="Chinese-Filipino exogamy",
                 "race_exog_extendedChinese.Japanese"="Chinese-Japanese exogamy",
                 "race_exog_extendedChinese.Korean"="Chinese-Korean exogamy",
                 "race_exog_extendedChinese.Vietnamese"="Chinese-Vietnamese exogamy",
                 "race_exog_extendedChinese.White"="Chinese-White exogamy",
                 "race_exog_extendedColombian.Cuban"="Colombian-Cuban exogamy",
                 "race_exog_extendedColombian.Dominican"="Colombian-Dominican exogamy",
                 "race_exog_extendedColombian.Ecuadorian"="Colombian-Ecuadorian exogamy",
                 "race_exog_extendedColombian.Guatemalan"="Colombian-Guatemalan exogamy",
                 "race_exog_extendedColombian.Mexican"="Colombian-Mexican exogamy",
                 "race_exog_extendedColombian.Peruvian"="Colombian-Peruvian exogamy",
                 "race_exog_extendedColombian.Puerto Rican"="Colombian-PR exogamy",
                 "race_exog_extendedColombian.Salvadorian"="Colombian-Salvadorian exogamy",
                 "race_exog_extendedColombian.White"="Colombian-White exogamy",
                 "race_exog_extendedCuban.Dominican"="Cuban-Dominican exogamy",
                 "race_exog_extendedCuban.Ecuadorian"="Cuban-Ecuadorian exogamy",
                 "race_exog_extendedCuban.Guatemalan"="Cuban-Guatemalan exogamy",
                 "race_exog_extendedCuban.Mexican"="Cuban-Mexican exogamy",
                 "race_exog_extendedCuban.Peruvian"="Cuban-Peruvian exogamy",
                 "race_exog_extendedCuban.Puerto Rican"="Cuban-PR exogamy",
                 "race_exog_extendedCuban.Salvadorian"="Cuban-Salvadorian exogamy",
                 "race_exog_extendedCuban.White"="Cuban-White exogamy",
                 "race_exog_extendedDominican.Ecuadorian"="Dominican-Ecuadorian exogamy",
                 "race_exog_extendedDominican.Guatemalan"="Dominican-Guatemalan exogamy",
                 "race_exog_extendedDominican.Mexican"="Dominican-Mexican exogamy",
                 "race_exog_extendedDominican.Peruvian"="Dominican-Peruvian exogamy",
                 "race_exog_extendedDominican.Puerto Rican"="Dominican-PR exogamy",
                 "race_exog_extendedDominican.Salvadorian"="Dominican-Salvadorian exogamy",
                 "race_exog_extendedDominican.White"="Dominican-White exogamy",
                 "race_exog_extendedEcuadorian.Guatemalan"="Ecuadorian-Guatemalan exogamy",
                 "race_exog_extendedEcuadorian.Mexican"="Ecuadorian-Mexican exogamy",
                 "race_exog_extendedEcuadorian.Peruvian"="Ecuadorian-Peruvian exogamy",
                 "race_exog_extendedEcuadorian.Puerto Rican"="Ecuadorian-PR exogamy",
                 "race_exog_extendedEcuadorian.Salvadorian"="Ecuadorian-Salvadorian exogamy",
                 "race_exog_extendedEcuadorian.White"="Ecuadorian-White exogamy",
                 "race_exog_extendedFilipino.Japanese"="Filipino-Japanese exogamy",
                 "race_exog_extendedFilipino.Korean"="Filipino-Korean exogamy",
                 "race_exog_extendedFilipino.Vietnamese"="Filipino-Vietnamese exogamy",
                 "race_exog_extendedFilipino.White"="Filipino-White exogamy",
                 "race_exog_extendedGuatemalan.Mexican"="Guatemalan-Mexican exogamy",
                 "race_exog_extendedGuatemalan.Peruvian"="Guatemalan-Peruvian exogamy",
                 "race_exog_extendedGuatemalan.Puerto Rican"="Guatemalan-PR exogamy",
                 "race_exog_extendedGuatemalan.Salvadorian"="Guatemalan-Salvadorian exogamy",
                 "race_exog_extendedGuatemalan.White"="Guatemalan-White exogamy",
                 "race_exog_extendedJapanese.Korean"="Japanese-Korean exogamy",
                 "race_exog_extendedJapanese.Vietnamese"="Japanese-Vietnamese exogamy",
                 "race_exog_extendedJapanese.White"="Japanese-White exogamy",
                 "race_exog_extendedKorean.Vietnamese"="Korean-Vietnamese exogamy",
                 "race_exog_extendedKorean.White"="Korean-White exogamy",
                 "race_exog_extendedMexican.Peruvian"="Mexican-Peruvian exogamy",
                 "race_exog_extendedMexican.Puerto Rican"="Mexican-PR exogamy",
                 "race_exog_extendedMexican.Salvadorian"="Mexican-Salvadorian exogamy",
                 "race_exog_extendedMexican.White"="Mexican-White exogamy",
                 "race_exog_extendedPeruvian.Puerto Rican"="Peruvian-PR exogamy",
                 "race_exog_extendedPeruvian.Salvadorian"="Peruvian-Salvadorian exogamy",
                 "race_exog_extendedPeruvian.White"="Peruvian-White exogamy",
                 "race_exog_extendedPuerto Rican.Salvadorian"="PR-Salvadorian exogamy",
                 "race_exog_extendedPuerto Rican.White"="PR-White exogamy",
                 "race_exog_extendedSalvadorian.White"="Salvadorian-White exogamy",
                 "race_exog_extendedVietnamese.White"="Vietnamese-White exogamy",
                 "race_filipino_latinoTRUE"="Filipino-Latino exogamy",
                 "bendog_all_firstTRUE"="Birthplace endogamy",
                 "bendog_partial_flex1.5TRUE"="Birthplace endogamy",
                 "language_endogTRUE"="Language endogamy")
```

```{r model-census-pentagon, results="asis"}
knitreg(lapply(models_census_pentagon, convertModel),
        digits=2,
        caption="Log-odds ratios from counterfactual marriage model predicting union formation on Census 1980 data using single ethnic exogamy term",
        caption.above=TRUE,
        custom.model.names=c("baseline","+birthplace","+language","+both"), 
        custom.coef.map=coef_map,
        dcolumn=TRUE, booktabs=TRUE, longtable=TRUE, threeparttable=TRUE)
```

```{r model-acs1980-pentagon, results="asis"}
knitreg(lapply(models_acs1980_pentagon, convertModel),
        digits=2,
        caption="Log-odds ratios from counterfactual marriage model predicting union formation on ACS 2014-18 data using single ethnic exogamy term and limited to Asian and Latino ethnic groups available in 1980",
        caption.above=TRUE,
        custom.model.names=c("baseline","+birthplace","+language","+both"), 
        custom.coef.map=coef_map,
        dcolumn=TRUE, booktabs=TRUE, longtable=TRUE, threeparttable=TRUE)
```

```{r model-acsfull-pentagon, results="asis"}
knitreg(lapply(models_acsfull_pentagon, convertModel),
        digits=2,
        caption="Log-odds ratios from counterfactual marriage model predicting union formation on ACS 2014-18 data using single ethnic exogamy term and all available Asian and Latino ethnic groups",
        caption.above=TRUE,
        custom.model.names=c("baseline","+birthplace","+language","+both"), 
        custom.coef.map=coef_map,
        dcolumn=TRUE, booktabs=TRUE, longtable=TRUE, threeparttable=TRUE)
```

```{r model-acsres-extended, results="asis"}
knitreg(lapply(models_acsres_extended, convertModel),
        digits=2,
        caption="Log-odds ratios from counterfactual marriage model predicting union formation on ACS 2014-18 data using ethnic-group specific terms and largest available Asian and Latino ethnic groups",
        caption.above=TRUE,
        custom.model.names=c("baseline","+birthplace","+language","+both"), 
        custom.coef.map=coef_map,
        dcolumn=TRUE, booktabs=TRUE, longtable=TRUE, threeparttable=TRUE)
```

```{r model-comparison, results="asis"}
knitreg(lapply(list(models_census_pentagon$both, 
                    models_census_pentagon_state$both,
                    models_acs1980_pentagon$both, 
                    models_acs1980_pentagon_state$both), convertModel),
        digits=2,
        caption="Comparison of log-odds ratios from counterfactual marriage models predicting union formation on Census 1980 and ACS 2014-18 data using single ethnic exogamy term and limited to Asian and Latino ethnic groups available in 1980 under different specifications of the marriage market.",
        caption.above=TRUE,
        custom.model.names=c("MSA+State 1980", "State 1980",
                             "MSA+State, 2014-18", "State, 2014-18"), 
        custom.coef.map=coef_map,
        dcolumn=TRUE, booktabs=TRUE, longtable=TRUE, threeparttable=TRUE)
```

```{r compare-time, fig.cap="Odds of ethnoracial exogamy relative to endogamy across two time periods. The panels compare the cases where marriage markets are defined either by a combination of MSA and state or by state alone. Results are based on models that control for age differences, educational differences, and birthplace and language endogamy. Values are sorted by ethnoracial exogamy in 1980. Arrows show the change across the two time periods based on comparable sets of ethnic groups. Results for American Indian/Alaska Native intermarriage are excluded due to sampling variability."}
bind_models <- function(models_summary) {
  temp <- lapply(models_summary, get_coefs) %>%
    bind_rows(.id="model") %>%
    filter(grepl("race_exog", variable))
  return(temp)
}

get_coefs <- function(x) {
  temp <- coef(x)[,c(1,2)]
  return(tibble(variable=rownames(temp), coef=temp[,1], se=temp[,2]))
}

coefs_pent <- list(census=models_census_pentagon,
                         acs_1980basis=models_acs1980_pentagon) %>%
  lapply(bind_models) %>%
  bind_rows(.id="data") %>%
  mutate(variable=convert_intermar_names(variable, "race_exog_pent"),
         model=factor(model,
                      levels=c("base","bendog","lendog","both"),
                      labels=c("Baseline model", "+ birthplace\nendogamy",
                               "+ language\nendogamy", "+ birthplace and\nlanguage endogamy")),
         data=factor(data,
                     levels=c("census","acs_1980basis"),
                     labels=c("Census 1980", 
                              "ACS 2014-18, 1980 ethnic groups"))) %>%
  order_variables("Census 1980", "+ both")

arrows_pent <- coefs_pent %>%
  filter(model=="+ birthplace and\nlanguage endogamy" & 
           variable!="South Asian ethnic exogamy" &
           data!="ACS 2014-18, all ethnic groups") %>%
  select(variable, coef, data) %>% 
  pivot_wider(names_from=data, values_from=coef) %>%
  rename(coef.census=`Census 1980`, 
         coef.acs=`ACS 2014-18, 1980 ethnic groups`)

coefs_pent_state <- list(census=models_census_pentagon_state,
                         acs_1980basis=models_acs1980_pentagon_state) %>%
  lapply(bind_models) %>%
  bind_rows(.id="data") %>%
  mutate(variable=convert_intermar_names(variable, "race_exog_pent"),
         model=factor(model,
                      levels=c("base","bendog","lendog","both"),
                      labels=c("Baseline model", "+ birthplace\nendogamy",
                               "+ language\nendogamy", "+ birthplace and\nlanguage endogamy")),
         data=factor(data,
                     levels=c("census","acs_1980basis"),
                     labels=c("Census 1980", 
                              "ACS 2014-18, 1980 ethnic groups"))) %>%
  order_variables("Census 1980", "+ both")

arrows_pent_state <- coefs_pent_state %>%
  filter(model=="+ birthplace and\nlanguage endogamy" & 
           variable!="South Asian ethnic exogamy" &
           data!="ACS 2014-18, all ethnic groups") %>%
  select(variable, coef, data) %>% 
  pivot_wider(names_from=data, values_from=coef) %>%
  rename(coef.census=`Census 1980`, 
         coef.acs=`ACS 2014-18, 1980 ethnic groups`)

coefs_pent$sensitive <- "MSA+State"
coefs_pent_state$sensitive <- "State"
coefs_pent <- rbind(coefs_pent, coefs_pent_state)

arrows_pent$sensitive <- "MSA+State"
arrows_pent_state$sensitive <- "State"
arrows_pent <- rbind(arrows_pent, arrows_pent_state)


coefs_pent %>%
  filter(model=="+ birthplace and\nlanguage endogamy" & 
           !grepl("South Asian ethnic exogamy", variable) & 
           !grepl("AIAN", variable)) %>%
  left_join(arrows_pent) %>%
  mutate(variable=str_replace(variable, "/", "-"),
         variable=str_replace(variable, "&","/"),
         variable=str_replace(variable, "E/SE Asian ethnic exogamy", "**E/SE Asian ethnic exogamy**"),
         variable=str_replace(variable, "Latino ethnic exogamy", "**Latino ethnic exogamy**"),
         coef=ifelse(data=="ACS 2014-18, all ethnic groups" & variable=="White/Black", NA, coef)) %>%
  order_variables("Census 1980", "+ birthplace and\nlanguage endogamy") %>%
  ggplot(aes(x=variable, y=exp(coef)))+
  geom_hline(yintercept = 1, linetype=3, size=1)+
  geom_point(aes(color=data, shape=data), alpha=1, size=3)+
  geom_segment(aes(x=variable, xend=variable,
                   y=exp(coef.census), yend=exp(coef.acs)),
               color="grey30",
               arrow = arrow(length = unit(0.03, "npc")))+
  coord_flip()+
  scale_y_continuous(limits=c(0,1.1), expand=c(0.01,0))+
  scale_color_manual(values = my_palette)+
  scale_shape_manual(values = c(16,16,17))+
  facet_grid(sensitive~.)+
  labs(x=NULL, 
       y="Odds ratio of exogamy relative to ethnoracial endogamy",
       title=NULL,
       color="Data source", shape="Data source")+
  theme_mine()+
  theme(axis.text.y=element_markdown())
```