---
title: "Word Tables"
author: "Aaron Gullickson"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, error = FALSE, 
                      warning = FALSE, eval = TRUE,
                      fig.height=3.5)
library(here)
source(here("analysis","check_packages.R"))
source(here("analysis","useful_functions.R"))
#load(here("analysis","output","models.RData"))
load(here("analysis","output","alternates.RData"))
load(here("analysis","output","models_bendog.RData"))

my_palette <- c("#7b3294","#008837","#a6dba0")

#instead of loading markets, which takes forever, hardcoding sample
#sizes but be sure to adjust if this changes
#load(here("analysis","output","markets_census.RData"))
#load(here("analysis","output","markets_acs_full.RData"))
#census_n <- sum(markets_census[[1]]$choice)
#acs_n <- sum(markets_acs_full[[1]]$choice)
census_n <- 285523
acs_n <- 503348

```

```{r sample-size-table}

temp <- c(table(alternates_acs$race)) %>% enframe()
tab_samp <- c(table(alternates_census$race)) %>% 
  enframe() %>%
  right_join(temp, by="name") %>%
  rename(ethnorace=name, census=value.x, acs=value.y) %>%
  mutate(
    ethnorace=ifelse(ethnorace=="AIAN","American Indian/Alaska Native",
                     ethnorace),
    race_big=case_when(
    ethnorace=="Chinese" ~ "East and Southeast Asian",
    ethnorace=="Japanese" ~ "East and Southeast Asian",
    ethnorace=="Korean" ~ "East and Southeast Asian",
    ethnorace=="Filipino" ~ "East and Southeast Asian",
    ethnorace=="Vietnamese" ~ "East and Southeast Asian",
    ethnorace=="Cambodian" ~ "East and Southeast Asian",
    ethnorace=="Hmong" ~ "East and Southeast Asian",
    ethnorace=="Laotian" ~ "East and Southeast Asian",
    ethnorace=="Thai" ~ "East and Southeast Asian",
    ethnorace=="Burmese" ~ "East and Southeast Asian",
    ethnorace=="Indonesian" ~ "East and Southeast Asian",
    ethnorace=="Malaysian" ~ "East and Southeast Asian",
    ethnorace=="Bhutanese" ~ "East and Southeast Asian",
    ethnorace=="Nepalese" ~ "East and Southeast Asian",
    ethnorace=="Asian Indian"  ~ "South Asian",
    ethnorace=="Pakistani" ~ "South Asian",
    ethnorace=="Bangladeshi" ~ "South Asian",
    ethnorace=="Sri Lankan" ~ "South Asian",
    ethnorace=="Mexican" ~ "Latino", 
    ethnorace=="Cuban" ~ "Latino", 
    ethnorace=="Puerto Rican" ~ "Latino", 
    ethnorace=="Guatemalan" ~ "Latino", 
    ethnorace=="Salvadorian" ~ "Latino", 
    ethnorace=="Dominican" ~ "Latino", 
    ethnorace=="Colombian" ~ "Latino", 
    ethnorace=="Costa Rican" ~ "Latino", 
    ethnorace=="Honduran" ~ "Latino", 
    ethnorace=="Nicaraguan" ~ "Latino", 
    ethnorace=="Panamanian" ~ "Latino", 
    ethnorace=="Argentinian" ~ "Latino", 
    ethnorace=="Bolivian" ~ "Latino", 
    ethnorace=="Chilean" ~ "Latino", 
    ethnorace=="Ecuadorian" ~ "Latino", 
    ethnorace=="Peruvian" ~ "Latino", 
    ethnorace=="Venezuelan" ~ "Latino", 
    ethnorace=="Paraguayan" ~ "Latino", 
    ethnorace=="Uruguayan"  ~ "Latino"
  ))

temp <- tab_samp %>% group_by(race_big) %>%
  summarize(census=sum(census, na.rm=TRUE), acs=sum(acs, na.rm=TRUE)) %>%
  na.omit() %>%
  rename(ethnorace=race_big)

tab_samp <- tab_samp %>% select(ethnorace, census, acs) %>%
  bind_rows(temp)

temp <- tibble(ethnorace="Marriages in the previous five years",
               census=census_n, acs=acs_n)

tab_samp <- tab_samp %>% 
  bind_rows(temp)
                    
ord <- c("Marriages in the previous five years",
         "White","Black","American Indian/Alaska Native","Latino",
         "Mexican","Puerto Rican","Cuban","Salvadorian","Dominican","Guatemalan",
         "Colombian","Honduran","Peruvian","Ecuadorian","Nicaraguan","Argentinian",
         "Venezuelan","Panamanian","Chilean","Costa Rican","Bolivian",
         "Uruguayan","Paraguayan",
         "East and Southeast Asian",
         "Chinese","Filipino","Vietnamese","Korean","Japanese","Cambodian",
         "Hmong","Laotian","Thai","Burmese","Indonesian","Malaysian",
         "South Asian",
         "Asian Indian","Pakistani","Bangladeshi","Sri Lankan")

tab_samp <- as.data.frame(tab_samp)
rownames(tab_samp) <- tab_samp$ethnorace
tab_samp <- tab_samp[ord,]
rownames(tab_samp) <- NULL

tab_samp <- tab_samp %>%
  tibble() %>%
  add_row(ethnorace="Marriages",census=NA,acs=NA, .before=1) %>%
  add_row(ethnorace="Alternate Partners",census=NA,acs=NA, .before=3)

tab_samp %>%
  flextable() %>%
  set_caption(caption = "Sample size of marriages and alternate partners by data source and ethnoracial category.") %>%
  set_header_labels(ethnorace="Category",census="Census 1980",acs="ACS 2014-18") %>%
  bold(i=c(1,3), j=1) %>%
  padding(i=c(2,4:7,27,40), j=1, padding.left=20) %>%
  padding(i=c(8:26,28:39,41:44), j=1, padding.left=40) %>%
  set_table_properties(layout = "autofit")  %>%
  add_footer_row(values = "Really long footnote just to get full width blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah blah ", colwidths = 3)
```

```{r block-diagram}
x <- rbind(c("(ref.)",rep("",7)),
           c("B/W","(ref.)",rep("",6)),
           c("A/W","A/B","(ref.)",rep("",5)),
           c("A/W","A/B","PE-A","(ref.)",rep("",4)),
           c("A/W","A/B","PE-A","PE-A","(ref.)",rep("",3)),
           c("L/W","L/B","L/A","L/A","L/A","(ref.)",rep("",2)),
           c("L/W","L/B","L/A","L/A","L/A","PE-L","(ref.)",rep("",1)),
           c("L/W","L/B","L/A","L/A","L/A","PE-L","PE-L","(ref.)"))
colnames(x) <- rownames(x) <- c("White","Black",
                                "Chinese","Japanese","Korean",
                                "Mexican","Cuban","Puerto Rican")

x %>%
  as_tibble() %>%
  add_column("x"=colnames(x), .before=1) %>%
  add_row(x="Asian", .before=3) %>%
  add_row(x="Latino", .before=7) %>%
  flextable() %>%
  set_caption(caption = "A schematic representation of the coding of ethnoracial exogamy for simplified models, using three example ethnicities for Asian and Latino populations. The table shows a crosstabulation of each partner's race. All parameters are gender-symmetric, so I only show the parameters below the diagonal. The reference category is an ethnoracially endogamous union. Each cell indicates the particular dummy variable that is applied to a given case. The terms measuring panethnicity are shown in bold.") %>%
  add_header_row(values = c("","Asian", "Latino"), colwidths = c(3, 3, 3)) %>%
  bold(c(3,7), 1) %>%
  bold(c(5,6), 4) %>%
  bold(6, 5) %>%
  bold(c(9,10), 7) %>%
  bold(10, 8) %>%
  padding(c(4:6,8:10), 1, padding.left = 20) %>%
  italic(2,1) %>%
  italic(3,2) %>%
  italic(4,3) %>%
  italic(5,4) %>%
  italic(6,5) %>%
  italic(7,6) %>%
  italic(8,7) %>%
  italic(9,8) %>%
  italic(10,9) %>%
  add_footer_row(values = "Notes: B/W=Black/White, A/W=Asian/White, A/B=Asian/Black, L/W=Latino/White, L/B=Latino/Black,L/A=Latino/Asian, PE-A=Panethnic Asian, PE-L=Panethnic Latino", colwidths = 9)
```


```{r deviance-bendog}
dev_acs <- sapply(models_bendog_acs, function(x) {mean(x$deviance)}) %>%
  enframe(name="model", value="deviance_acs")

tab_dev <- sapply(models_bendog_census, function(x) {mean(x$deviance)}) %>%
  enframe(name="model", value="deviance_census") %>%
  left_join(dev_acs) %>%
  mutate(gen1.75=c("Birthplace","USA","Both","USA","USA","USA","USA", "USA", 
                   "Both","Both"),
         gen1.5 =c("Birthplace","USA","Both","Both","Birthplace","USA","Both",
                   "USA", "Birthplace","Both"),
         gen1.25=c("Birthplace","USA","Both","Birthplace","Birthplace",
                   "Birthplace","Both","Both","Birthplace","Birthplace")) %>%
  select(gen1.25, gen1.5, gen1.75, deviance_census, deviance_acs) %>%
   relocate(gen1.75, gen1.5, gen1.25, deviance_census, deviance_acs) %>%
   arrange(gen1.25, gen1.5, gen1.75) 

tab_dev %>%
  flextable() %>%
  set_caption(caption = "Model fit to Census 1980 and ACS data using different specifications of birthplace endogamy for 1.25, 1.5, and 1.75 generations. Minimum deviance is shown in bold.") %>%
  set_header_labels(gen1.75="1.75",gen1.5="1.5",gen1.25="1.25",
                    deviance_census="Census 1980", deviance_acs="ACS 2014-18") %>%
  bold(i=1, j=4) %>%
  bold(i=4, j=5) %>%
  set_table_properties(layout = "autofit") %>%
  add_header_row(values = c("Generation", "Model Deviance"), colwidths = c(3, 2)) %>%
  add_footer_row(values = "Notes: Age of US arrival by generation is 0-5 (1.75), 6-12 (1.5), and 13-17 (1.25). All models include controls for educational differences, age differences, ethnoracial endogamy, and language endogamy.", colwidths = 5)
```
